/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yellingapp;

import java.util.Properties;

import org.apache.kafka.common.serialization.Serde;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.StreamsConfig;
import org.apache.kafka.streams.kstream.Consumed;
import org.apache.kafka.streams.kstream.KStream;

public class App {
    public String getGreeting() {
        return "Hello World! Happy New Year Day! 2024";
    }

    public static void main(String[] args) {
        new App().Run();
    }

    public void Run(){
        
        Properties props = new Properties();
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "yelling_app_id");
        props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");

        StreamsConfig strmConfig = new StreamsConfig(props);
        Serde<String> strSerde = Serdes.String();
        StreamsBuilder builder = new StreamsBuilder();

        KStream<String, String> simpleFirstStream = builder.stream("src-topic", Consumed.with(strSerde, strSerde));
    }
}
